version: '1'
volumes:
  pgdata:
  static_files:
  frontend_files:
services:
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=django.settings.prod
      - PYTHONUNBUFFERED=1
    volumes:
      - static_files:/static_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 django.wsgi -b 0.0.0.0:8000
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: blog
      POSTGRES_PASS: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_files
      - frontend_files:/var/www/
    ports:
      - 80:80
