# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
