# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200114_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
