# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userregistration_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
