# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200119_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
