# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_authtoken_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='term',
            field=models.BooleanField(default=False),
        ),
    ]
