# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-08 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('token_access', models.TextField(blank=True, null=True)),
                ('token_refresh', models.TextField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('terms', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='authtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='token',
        ),
        migrations.AddField(
            model_name='account',
            name='token_access',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='token_refresh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
