# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-08 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_auto_20200308_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='password',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
